language: node_js
node_js:
- '4.1'
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - vendor
before_install:
  - rvm install `cat .ruby-version`
install:
  - npm install
script:
  - npm run build
after_success:
  - npm run-script deploy
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
